### ISSUE TITLE
Change warning logs to debug logs

### ISSUE THREAD

**Issue by cdouine39** [IBM-Bluemix/gp-angular-client#23]
Hi,

when the user's language is not available in the bundles, warning logs are displayed in the console. Those logs come from L 240 and L 277 : 
logWarning("[normalizeLanguage] fallback returned null...using source lang");

When there's a lot of translations done on one page, this slows down the page. 
I tested with changing this to : 
DEBUG && logDebug("[normalizeLanguage] fallback returned null...using source lang");
that makes the page run much faster. 

Would you agree to do that change ?
I'd be happy to do it, if you're fine with it.

Thanks,
Camille

**Comment by srl295** [comment]
fixed in #24
